# Generated by Django 3.2.4 on 2021-06-18 05:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('verticals', '0002_parameter_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constraint',
            name='endpoints',
        ),
        migrations.AddField(
            model_name='constraint',
            name='endpoints',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='verticals.endpoint'),
            preserve_default=False,
        ),
    ]
