# Generated by Django 3.2.4 on 2021-06-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verticals', '0003_auto_20210618_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='description',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
